name: setup
description: Setup Node and install dependencies

inputs:
  node_version:
    description: Node Version
    required: true

runs:
  using: composite
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3

    - name: Use Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    - name: 💼 Cache pnpm modules
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: 🔧 Install dependencies
      uses: pnpm/action-setup@v2.4.0
      with:
        version: 8.15.x
        run_install: |
          - args: [--frozen-lockfile, --strict-peer-dependencies]
